### ISSUE TITLE
Week 2 - Robot Deliverables 

### ISSUE THREAD

**Issue by nVarap** [The-Code-Monkeys/Monkeys38#3]
# To-Do
- [ ] Begin Construction
- [ ] Begin Socket.io connection
- [ ] Begin drivetrain code

# Deliverables
- [ ] Get 50% through construction (aim to finish in one week)
- [ ] Get 25% through hardware (aim to finish)
- [ ] Finish 10% of socket.io (get client running
- [ ] Be almost done with drivetrain code (aim to finish for testing next week)
