### ISSUE TITLE
Week 3 - Robot Deliverables

### ISSUE THREAD

**Issue by nVarap** [The-Code-Monkeys/Monkeys38#4]
# Todo
- [ ] Complete **entire bot**
- [ ] Complete **all hardware**
- [ ] Complete drivetrain *test if possible*
- [ ] Socket 75%-80% completed

# Deliverables
- [ ] Bot entirely completed
- [ ] Drivetrain code tested, connecting starting to form between back and frontend
- [ ] Web application on its way - @DeadshotLegend and @nVarap pivot to web app to assist coders
