### ISSUE TITLE
Week 4 - Robot Deliverable

### ISSUE THREAD

**Issue by nVarap** [The-Code-Monkeys/Monkeys38#5]
# Todo
- [ ] ***TEST TEST TEST***
- [ ] Make sure stress testing is all goo
- [ ] Keep track of trials in notion
- [ ] Update aesthetics of anything
- [ ] try *not* to break everything before N@TM

# Deliverables
- [ ] everything. If this is not checked, Houston we have a problem.
- [ ] If anything else, aesthetics
